const mongoose=require('mongoose');

const ProductSchema= mongoose.Schema({
    image:{
        type:Buffer,
        default: "iVBORw0KGgoAAAANSUhEUgAABAAAAAQACAIAAADwf7zUAAAQAElEQVR4Aey9B5gsR3U2fE5Vd8/M7t6kHMBgjInGv3HiAz5sgwNO2w4wzDLMsMwwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDMMswwzDDM",

    },
    name:String,
    price:Number,
    discount:{
        type:Number,
        default:0
    },
    bgcolor:String,
    panelcolor:String,
    textcolor:String
});

module.exports=mongoose.model('Product',ProductSchema);